baseURL = "https://www.jivarsound.com"
title = "j.ivar sound"
copyright = "j.ivar sound., All Rights Reserved. MIT License."
languageCode = "en-us"
googleAnalytics = "UA-120278356-1"
paginate = 5

[params]
  AuthorName = "Jason I. Aizkalns"
  GitHubUser = "JasonAizkalns"

[author]
  name = "Jason I. Aizkalns"

[permalinks]
  # :title is used if :slug is not defined in post frontmatter
  blog = "/:section/:year/:month/:slug/"
