baseURL = "https://www.jivarsound.com"
title = "j.ivar sound"
copyright = "j.ivar sound., All Rights Reserved. MIT License."
rssLimit = 25
languageCode = "en-us"
# googleAnalytics = "UA-120278356-1"

[pagination]
  pagerSize = 5

[params]
  [params.author]
    name = "Jason I. Aizkalns"
    email = "j.ivar.sound@gmail.com"

[permalinks]
  # :title is used if :slug is not defined in post frontmatter
  # blog = "/:section/:year/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


