baseURL = "https://www.jivarsound.com"
languageCode = "en-us"
title = "j.ivar sound"

googleAnalytics = "UA-120278356-1"

paginate = 5

[params]
  AuthorName = "Jason I. Aizkalns"
  GitHubUser = "JasonAizkalns"
